[package]
name = "golem-rpc-api"
version = "0.1.0"
authors = ["Przemysław K. Rekucki <przemyslaw.rekucki@golem.network>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_repr = "0.1"
serde_json = "1.0"
futures="0.1"
log="0.4"
failure="0.1"

bigdecimal = {version = "0.1.0", features=["serde"]}
chrono = {version = "0.4.6", features=["serde"]}

[dependencies.actix-wamp]
path="../actix-wamp"

[dependencies.tokio-timer]
version = "0.2.11"

[dependencies.golem-rpc-macros]
path="../golem-rpc-macros"

[dependencies.num-traits]
version = "0.2"

[dependencies.openssl]
version="0.10.20"
features=['vendored']

[features]
default=["settings"]
settings=[]
