[package]
name = "golem-rpc-api"
version = "0.1.0"
authors = ["Przemysław K. Rekucki <przemyslaw.rekucki@golem.network>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wamp-derive={path= "../wamp-derive"}
futures="0.1"