os: Visual Studio 2017
environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -yv --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - rustup component add rustfmt
build: false
test_script:
  - cargo fmt --all -- --check
  - cargo build --release
  - cargo build
  - cargo test