(function() {var implementors = {};
implementors["golem_rpc_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/serde_json/1.0.40/serde_json/error/struct.Error.html\" title=\"struct serde_json::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"golem_rpc_api/enum.Error.html\" title=\"enum golem_rpc_api::Error\">Error</a>",synthetic:false,types:["golem_rpc_api::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"golem_rpc_api/rpc/wamp/enum.Error.html\" title=\"enum golem_rpc_api::rpc::wamp::Error\">Error</a>&gt; for <a class=\"enum\" href=\"golem_rpc_api/enum.Error.html\" title=\"enum golem_rpc_api::Error\">Error</a>",synthetic:false,types:["golem_rpc_api::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"golem_rpc_api/enum.Error.html\" title=\"enum golem_rpc_api::Error\">Error</a>",synthetic:false,types:["golem_rpc_api::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/openssl/0.10/openssl/error/struct.ErrorStack.html\" title=\"struct openssl::error::ErrorStack\">ErrorStack</a>&gt; for <a class=\"enum\" href=\"golem_rpc_api/enum.Error.html\" title=\"enum golem_rpc_api::Error\">Error</a>",synthetic:false,types:["golem_rpc_api::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
